services:
  # DB
  board-db:
    container_name: board-db
    image: postgres:15
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=board-db
  #=================================
  teamboard-api:
    depends_on:
      - board-db
    container_name: teamboard-api
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL_PROD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SECRET_JWT=${SECRET_JWT}
