services:
  # DB
  board-db:
    container_name: board-db
    image: postgres:15
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=board-db
    # ⭐ AÑADIDO: Healthcheck para verificar que PostgreSQL está listo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d board-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  #=================================
  teamboard-api:
    depends_on:
      board-db:
        condition: service_healthy  # ⭐ MODIFICADO: Esperar a que la DB esté saludable
    image: teamboard-api-prod
    ports:
      - ${PORT}:${PORT}
    build:
      context: ./
      dockerfile: dockerfile.prod
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL_PROD}