apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: teamboard
  name: teamboard
spec:
  ports:
    - name: '3000'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: teamboard-api
  type: NodePort
status:
  loadBalancer: {}